export {Gyro};

//The gyro class contains the 3 Axis rotation data of the gyro.  For testing purposes the values are placeholders generated by a sine wave

let testModifier = 0;
const sensitivity = 0.1;
class Gyro {
    constructor() {
        this.x = 0;
        this.y = 0;
        this.z = 0;
        this.lastRotation = [0,0,0];
        this.readArray = function(){
            return [this.x, this.y, this.z];
        }
        this.isMoving = function(){
        //TODO: isMoving function
        // this function returns true if the magnatutide of the gyro's rotations is greater than the sensitivity value
            
        }
        this.testRotation = function(x){
            this.testModifier += x;
            this.x = Math.sin(this.testModifier);
            this.y = Math.sin(this.testModifier*2);
            this.z = Math.sin(this.testModifier/3);
        }
    }
}