
//The gyro class contains the 3 Axis rotation data of the gyro.  For testing purposes the values are placeholders generated by a sine wave

class Gyro {
  constructor() {
    this.testModifier = 0.0;
    this.sensitivity = 5;
    this.x = 0.0;
    this.y = 0.0;
    this.z = 0.0;
    this.lastRotation = [0.0, 0.0, 0.0];
    this.readArray = function () {
      return [this.x, this.y, this.z];
    };

    this.isMoving = function () {
      //TODO: isMoving function
      // this function returns true if the difference between the current rotation and the last rotation that was true has a magnitude greater than the sensitivity level

        let magnitude = Math.sqrt(
          this.x * this.x + this.y * this.y + this.z * this.z
        );

        let result = magnitude > this.sensitivity;
        
        if (result) {
          this.lastRotation = [this.x, this.y, this.z];
        }
      return result;
    };
    this.testRotation = function (x) {
      this.testModifier += x;
      this.x = Math.sin(this.testModifier)/Math.PI*180;
      this.y = Math.sin(this.testModifier * 2)/Math.PI *180;
      this.z = Math.sin(this.testModifier / 3)/Math.PI *180;
    };
  }
}
export {Gyro};
